### ISSUE TITLE
CopyleaksExportModel verifying params backwards

### ISSUE THREAD

**Issue by dtredger-tuw** [Copyleaks/Ruby-Plagiarism-Checker#3]
https://github.com/Copyleaks/Ruby-Plagiarism-Checker/blob/13cf27c9391d566de3470fc5c756e590738fcce0/lib/copyleaks/models/exports/export_model.rb#L49

When initializing a new CopyleaksExportModel, **_initialize_** checks the params are the correct type. However, the check for pdfReport looks like above:

I believe this is backwards—it should be rejecting pdfReport if it is _not_ an instance of ExportPdfReport

I think the checks for **_maxRetries_** and **_developerPayload_** have the same issue

**Comment by AvichaiCopyleaks** [comment]
Thanks for reporting.
issue is now fixed.
